### PR TITLE
Add subject to message

### LINKED ISSUE #79: Subject and Message is empty when receiving message from queue that was published with sns
Hi,
thanks for the project. I'm having an issue when receiving a message from SQS that was published by SNS:

```
sebastian:~/Development/message$ aws --endpoint-url http://localhost:4100 sns create-topic --name something-happend
{
    "TopicArn": "arn:aws:sns:local:000000000000:something-happend"
}
sebastian:~/Development/message$ aws --endpoint-url http://localhost:4100 sqs create-queue --queue-name something-happened
{
    "QueueUrl": "http://localhost:4100/queue/something-happened"
}
sebastian:~/Development/message$ aws --endpoint-url http://localhost:4100 sns subscribe --topic-arn arn:aws:sns:local:000000000000:something-happend --protocol sqs --notification-endpoint http://localhost:4100/queue/something-happened
{
    "SubscriptionArn": "arn:aws:sns:local:000000000000:something-happend:41846153-40d1-42fc-af39-649b48bac0fb"
}
sebastian:~/Development/message$ aws --endpoint-url http://localhost:4100 sns publish --topic-arn arn:aws:sns:local:000000000000:something-happend --subject test --message test
{
    "MessageId": "c91ac05a-be13-4a4a-9d04-8646274b0389"
}
sebastian:~/Development/message$ aws --endpoint-url http://localhost:4100 sqs receive-message --queue-url http://localhost:4100/something-happened
{
    "Messages": [
        {
            "ReceiptHandle": "29f556cc-79b8-4f1e-b3b8-7d34e121a9b2#fa293d47-48ef-4402-8173-43f2df13b1d6",
            "MessageId": "29f556cc-79b8-4f1e-b3b8-7d34e121a9b2",
            "Body": "{\"Type\":\"Notification\",\"MessageId\":\"9f967ab3-dce0-4667-93f2-20032cb409d2\",\"TopicArn\":\"arn:aws:sns:local:000000000000:something-happend\",\"Subject\":\"\",\"Message\":\"\",\"TimeStamp\":\"2016-12-22T10:12:26:012Z\\n\"}",
            "MD5OfBody": "b49c3ab34610f6ac60fa57006fe040ef"
        }
    ]
}
sebastian:~/Development/message$ aws --endpoint-url http://localhost:4100 sqs receive-message --queue-url http://localhost:4100/something-happened
```

Problem is that `Subject` and `Message` is empty when receiving the message from SQS.

Am I doing something wrong or is that not implemented (yet)?

### PR DESCRIPTION
**Pull request by splagemann**
This fixes #79

### CODE REVIEW

**Comment by splagemann** [comment]
Please also update docker image

**Comment by p4tin** [comment]
Please fix the unit tests to include the Subject and also confirm on receipt that the subject is present.  Thanks!

**Comment by splagemann** [comment]
sure will do that. thanks for getting back to me

**Comment by splagemann** [comment]
Hey @p4tin,
do you think you can review this today?

**Comment by p4tin** [comment]
@splagemann - I am away until the 4th, I have reviewed and will be merging both PRs at that time and creating a new docker image as well.  Cheers!!

**Comment by p4tin** [comment]
Sorry it took so long - I will create a new docker image soon

**Pull request merged**
