### PR TITLE
Add two port config for yopa and or (fake-sns + fake-sqs) compatibility

### PR DESCRIPTION
**Pull request by p4tin**
- Added 2 port congigurating in yaml
 - Remove the port option from the command line.

### CODE REVIEW

**Comment by p4tin** [comment]
@tomasbartkus - Review and let me know if this is what you intended..  Note that in the 2 port config it does not matter which port you use for what they both fully support the entire API.

**Comment by p4tin** [comment]
@tomasbartkus - let me know if this is what you intended...  Note that in the two port config both ports support the full API so they are interchangeable.

**Comment by tomasbartkus** [comment]
Yep, i am preparing PR :)

**Comment by p4tin** [comment]
@tomasbartkus this is the PR ;)

**Pull request merged**
